### PR TITLE
Updated identity-66e and pap-f8d extension files

### PR DESCRIPTION
**Pull request by ghackford-mitre**
Fork contains the updated API and test files for identity-66e and pap-f8d. It also contains the pyproject, tox, README, and example files.

### CODE REVIEW

**Comment by rpiazza** [comment]
Please rename the pap directory as pap-marking-definition-f8d

You need to add code in https://github.com/ghackford-mitre/cti-python-stix2-extensions/blob/main/.github/workflows/tests.yml for your two extensions

**Comment by ghackford-mitre** [comment]
directory name has been updated and code was added to the github tests.yml file

**Comment by rpiazza** [comment]
Take a closer look at the tests.yml file - you need to add more stuff :-)

When you commit - it should run your tests in your fork

**Comment by rpiazza** [comment]
I think: - 'pap-marking-definition-f8d**/' should be - 'pap-marking-definition-f8d/**', which might be why those tests didn't run.

**Pull request merged**
